---
swagger: "2.0"
info:
  description: "testes"
  version: "1.0.0"
  title: "testes API"
host: "localhost:9090"
basePath: "/v1/sbe"
schemes:
- "http"
produces:
- "application/json"
paths:
  /midia/tipo-midia:
    get:
      tags:
      - "rds"
      summary: "RDS - 3.083 Tipo de Mídia."
      description: "teste"
      responses:
        200:
          description: "teste"
          schema:
            $ref: 'TipoMidia.yaml'




